### PR TITLE
Light Volume

### PR DESCRIPTION
**Pull request by Setekh**
I made it like this:
- DLight extends Geometry, the mesh of the geometry is generated in the constructor of a implementer of the DLight class
- DLight has 3 abstract methods: 
  1. clean()[which handles the removal of the volume light, and other things that need to be cleaned].
  2. initiate() , which will create the material for the object
  3. updateAndGetMaterial() ,that will be called whenever the light changes have been done from the jme3 light, not ours, it's also runned when the material is set to the volume and the line of the initiation method of the scene processor.
- DeferredSceneProcessor: Has now some methods that handle the add-ing of a light, parsing a node for lights and adding themm to the lightNode of the scene processor, lightNode tho must not be accessed outside, since it will only have the volume lights added to it and it will be managed by the scene processor only.

Think i covered everything important.. fetch me and see if you're liking it i am open for changes and looking forward on your opinions about this.

### CODE REVIEW

**Comment by kwando** [comment]
I'm gonna try this out =)

**Comment by Setekh** [comment]
I'm gonna do now spot lights, with the cone mesh u made on the other project. Maybe even do a cookie method for it while im at it.

**Comment by kwando** [comment]
Hmm, I got worrying performance out of this =S Something is terribly slow... =S

With the master branch version I can render 40x40 cubes and 40x40 lights at 60 fps. When using this version there I get about 1-2 fps =S

**Comment by Setekh** [comment]
that's stupid.. it's not like it's updating material/ mesh data continuously.. maybe its from my shader changes?

**Comment by kwando** [comment]
I have not found the issue yet..

**Comment by Setekh** [comment]
darn, im at work so.. wont be able to fix it till morning (+2h GMT here), thing is for me its fast and actually faster since the point light volume(sphere) is 96 triangles while the icosphere j3o is 120, cant really understand why it will go slower. (currently browsing code)

**Comment by kwando** [comment]
Have you increased the size of the bounding volumes?

**Comment by Setekh** [comment]
size as in scale?

**Comment by kwando** [comment]
Size as in screen space size.

11 nov 2012 kl. 17:21 skrev Setekh notifications@github.com:

**Comment by Setekh** [comment]
well i concluded from ur test case light radius to be 0.05f and the scale of the object u had there was 5f and logic dictates that the radius of the volume should be volume scale / 100f. Not sure if that's the issue.. since it look pretty accurate, icosphere/sphere.
See DPointLight#updateAndGetMaterial();

Edit: If it's not from the volume then maybe it's cus im still using lightlists.. if you could comment them out..and see what it dose.

**Comment by kwando** [comment]
yes, I'm using your pull vanilla. (only changed the number of cubes and lights). The scale looks about right when I turn on debug meshes... so I guess that's not the issue either =S

Yes, I'm using a mac =P

**Comment by Setekh** [comment]
Just found the issue -.-, it was the light list. Im gonna rethink this..

**Comment by kwando** [comment]
Yeah, I saw that light list also. I do not think we need to add to that list..

**Comment by kwando** [comment]
I've done some minor updates and refactoring of the DefferedRenderingProcessor. Consider rebase your work on top of them.

**Comment by Setekh** [comment]
yeah, well i thought ill use it to hold all the ambient lights to calculate the ambient color.. and also to keep the other lights we might need them later on, and it would be easier to get then iterate through the light volumes, but apparently its stupid, sorry for the inconvenience. I just dropped the light list thingy now it uses only the volume lights and 1 single ambient light, and if more ambient lights are added the color will add to the main one.. but i don't really think we need more ambient lights.. we can just mult the color.. feel free to delete that. I am currently doing more tests performance/error checking.

I will update ofc =P

**Comment by kwando** [comment]
Yeah. I'm thinking of generating the shader for the ambient/directional pass instead of hard coding it like now. One can easily fit several directional lights, ambient, rim, hemispherical etc lights into the same shading pass. It would definitely be faster than doing a fullscreen pass for each of them =)

btw you do not need to be up to date on the dev branch if you do not want, just the master branch =)

**Comment by Setekh** [comment]
God damn it, this is the first time i use git, so sorry if i look clumsy.

**Comment by kwando** [comment]
No problem, I've only used it for private projects so far. We will learn by doing =)

**Pull request closed without merging**
